# Generated by Django 4.0.6 on 2022-07-15 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='winner'),
            preserve_default=False,
        ),
    ]
