# Generated by Django 4.0.6 on 2022-07-15 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0002_game_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='winner'),
        ),
    ]
