# Generated by Django 4.0.6 on 2022-07-15 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0003_alter_game_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], default='first', max_length=7, verbose_name='in turn'),
        ),
        migrations.AlterField(
            model_name='game',
            name='win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='winner'),
        ),
    ]
