# Generated by Django 4.0.6 on 2022-07-15 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.CharField(choices=[('first', 'first'), ('second', 'second')], max_length=7, verbose_name='in turn')),
                ('first_pl_points', models.PositiveSmallIntegerField(default=0, verbose_name='first player points')),
                ('second_pl_points', models.PositiveSmallIntegerField(default=0, verbose_name='second player points')),
                ('first_pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to=settings.AUTH_USER_MODEL, verbose_name='first player')),
                ('second_pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to=settings.AUTH_USER_MODEL, verbose_name='second player')),
            ],
        ),
    ]
